language: php

php:
 - 5.5
 - 5.6
 - 7.0
 - 7.1
 - 7.2

before_script:
 - travis_retry composer self-update
 - travis_retry composer install --dev --no-interaction

script:
# - mkdir -p build/logs
 - phpunit --coverage-clover coverage.clover

after_script:
# - php vendor/bin/coveralls -v
 - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

